# Generated by Django 3.2.25 on 2025-03-27 18:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KeywordAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=50)),
                ('occurrences', models.IntegerField(default=0)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Keyword Analytics',
            },
        ),
        migrations.CreateModel(
            name='MessageAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=10)),
                ('period_start', models.DateTimeField()),
                ('message_type', models.CharField(choices=[('all', 'All Messages'), ('text', 'Text Messages'), ('soft_delete', 'Soft Deleted Messages')], max_length=20)),
                ('message_count', models.IntegerField(default=0)),
                ('unique_senders', models.IntegerField(default=0)),
                ('unique_receivers', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Message Analytics',
            },
        ),
        migrations.CreateModel(
            name='UserActivityAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('messages_sent', models.IntegerField(default=0)),
                ('messages_received', models.IntegerField(default=0)),
                ('last_activity', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'User Activity Analytics',
            },
        ),
        migrations.AddIndex(
            model_name='useractivityanalytics',
            index=models.Index(fields=['username'], name='kafka_app_u_usernam_8f2bb5_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivityanalytics',
            index=models.Index(fields=['last_activity'], name='kafka_app_u_last_ac_9f1e35_idx'),
        ),
        migrations.AddIndex(
            model_name='messageanalytics',
            index=models.Index(fields=['period', 'period_start'], name='kafka_app_m_period_9ba05f_idx'),
        ),
        migrations.AddIndex(
            model_name='messageanalytics',
            index=models.Index(fields=['message_type'], name='kafka_app_m_message_b6c244_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='messageanalytics',
            unique_together={('period', 'period_start', 'message_type')},
        ),
        migrations.AddIndex(
            model_name='keywordanalytics',
            index=models.Index(fields=['keyword'], name='kafka_app_k_keyword_a839ab_idx'),
        ),
        migrations.AddIndex(
            model_name='keywordanalytics',
            index=models.Index(fields=['occurrences'], name='kafka_app_k_occurre_597473_idx'),
        ),
    ]
