# Generated by Django 5.0 on 2025-03-26 22:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="KafkaMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField(verbose_name="الرسالة")),
                (
                    "timestamp",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="وقت الاستلام"
                    ),
                ),
            ],
            options={
                "verbose_name": "رسالة Kafka",
                "verbose_name_plural": "رسائل Kafka",
                "ordering": ["-timestamp"],
            },
        ),
    ]
