# Generated by Django 5.0 on 2025-03-26 23:01

import kafka_app.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kafka_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="kafkamessage",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=kafka_app.models.get_file_upload_path,
                verbose_name="الملف",
            ),
        ),
        migrations.AddField(
            model_name="kafkamessage",
            name="file_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="اسم الملف"
            ),
        ),
        migrations.AddField(
            model_name="kafkamessage",
            name="file_size",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="حجم الملف (بايت)"
            ),
        ),
        migrations.AddField(
            model_name="kafkamessage",
            name="file_type",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="نوع الملف"
            ),
        ),
        migrations.AddField(
            model_name="kafkamessage",
            name="message_type",
            field=models.CharField(
                choices=[("text", "رسالة نصية"), ("file", "ملف")],
                default="text",
                max_length=10,
                verbose_name="نوع الرسالة",
            ),
        ),
        migrations.AlterField(
            model_name="kafkamessage",
            name="message",
            field=models.TextField(blank=True, null=True, verbose_name="الرسالة"),
        ),
    ]
