# Generated by Django 3.2.25 on 2025-03-27 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kafka_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageLifetimeAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lifetime_range', models.CharField(choices=[('0-1', 'Less than 1 minute'), ('1-5', '1-5 minutes'), ('5-15', '5-15 minutes'), ('15-30', '15-30 minutes'), ('30-60', '30-60 minutes'), ('60-180', '1-3 hours'), ('180-360', '3-6 hours'), ('360-720', '6-12 hours'), ('720-1440', '12-24 hours'), ('1440+', 'More than 24 hours')], max_length=10)),
                ('message_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Message Lifetime Analytics',
            },
        ),
        migrations.AddIndex(
            model_name='messagelifetimeanalytics',
            index=models.Index(fields=['lifetime_range'], name='kafka_app_m_lifetim_1f471e_idx'),
        ),
    ]
