# Generated by Django 5.0 on 2025-03-26 23:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kafka_app", "0003_kafkamessage_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="kafkamessage",
            name="topic",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="الموضوع"
            ),
        ),
    ]
